TreasureTrove/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/',
         include('social_django.urls', namespace='social')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
                                     name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('create/', views.product_create, name='create'),
    path('delete/', views.product_delete, name='delete'),
    path('', views.product_list_shop, name='product_list_shop'),
    path('market/', views.product_list_market, name='product_list_market'),
    path('ranking/', views.product_ranking, name='product_ranking'),
    path('<slug:category_slug>/', views.product_list_shop,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail_shop,
         name='product_detail_shop'),
    path('product/like/', views.product_like, name='product_like'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/footer.css' %}" rel="stylesheet">
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link href="{% static "css/cart.css" %}" rel="stylesheet">
    <link href="{% static "css/header.css" %}" rel="stylesheet">
    <link href="{% static "css/detail.css" %}" rel="stylesheet">
    <link href="{% static "css/list_user.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous">
</head>
<body>
  {% include "header.html" %}

  {% block content %}
  {% endblock %}

  {% include "footer.html" %}

  <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
  <script>
    const csrftoken = Cookies.get('csrftoken');
    document.addEventListener('DOMContentLoaded', (event) => {
      // DOM loaded
      {% block domready %}
      {% endblock %}
    });
  </script>
</body>
</html>

templates/footer.html
</div>
<footer>
  <div class="footer-container">
    <div class="footer-section">
      <h3>Get to Know Us</h3>
      <ul>
        <li><a href="#">About Us</a></li>
        <li><a href="#">Careers</a></li>
        <li><a href="#">Press Releases</a></li>
        <li><a href="#">TreasureTrove Cares</a></li>
        <li><a href="#">Gift a Smile</a></li>
      </ul>
    </div>

    <div class="footer-section">
      <h3>Connect with Us</h3>
      <ul>
        <li><a href="#">Facebook</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Instagram</a></li>
      </ul>
    </div>

    <div class="footer-section">
      <h3>Make Money with Us</h3>
      <ul>
        <li><a href="#">Sell on TreasureTrove</a></li>
        <li><a href="#">Sell under TreasureTrove Accelerator</a></li>
        <li><a href="#">Become an Affiliate</a></li>
        <li><a href="#">Advertise Your Products</a></li>
      </ul>
    </div>

    <div class="footer-section">
      <h3>Let Us Help You</h3>
      <ul>
        <li><a href="#">Your Account</a></li>
        <li><a href="#">Returns Centre</a></li>
        <li><a href="#">100% Purchase Protection</a></li>
        <li><a href="#">Help</a></li>
      </ul>
    </div>
  </div>

  <div class="footer-bottom">
    <div class="footer-bottom-left">
      <a href="#">Conditions of Use & Sale</a>
      <a href="#">Privacy Notice</a>
      <a href="#">Interest-Based Ads</a>
    </div>
    <div class="footer-bottom-right">
      <p>&copy; 2023 Your Company Name. All rights reserved.</p>
    </div>
  </div>
</footer>
  {% block content %}
  {% endblock %}
</body>
</html>

templates/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/base.css" %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous">
</head>
<body>
  <div id="header">
    <span class="logo">TreasureTrove</span>
    {% if request.user.is_authenticated %}
      <ul class="menu">
        <li {% if section == "shop" %}class="selected"{% endif %}>
          <a href="{% url "shop" %}">My shop</a>
        </li>
        <li {% if section == "marketplace" %}class="selected"{% endif %}>
          <a href="{% url "shop:product_list_market" %}">Marketplace</a>
        </li>
        <li {% if section == "people" %}class="selected"{% endif %}>
          <a href="{% url "user_list" %}">Shops</a>
        </li>
        <li {% if section == "settings" %}class="selected"{% endif %}>
          <a href="{% url "settings" %}">Settings</a>
        </li>
      </ul>
    {% endif %}
    <div class="search-bar">
      <input type="text" placeholder="Search...">
      <button><i class="fas fa-search"></i></button>
    </div>
    <span class="user">
      {% if request.user.is_authenticated %}
        <div class="cart-header">
          {% with total_items=cart|length %}
            {% if total_items > 0 %}
              Your cart:
              <a href="{% url "cart:cart_detail" %}">
                {{ total_items }} item{{ total_items|pluralize }},
                ${{ cart.get_total_price }}
              </a>
            {% else %}
              Your cart is empty.
            {% endif %}
          {% endwith %}
        </div>
    <span class="bell-icon">&#128276;</span>
        Hello {{ request.user.first_name|default:request.user.username }},
      <div class="user-avatar">
        {% if request.user.profile.photo %}
          <img src="{{ request.user.profile.photo.url }}" alt="User Avatar">
        {% else %}
          <img src="{% static 'img/no_img.png' %}" alt="Default Avatar">
        {% endif %}
      </div>
        <a href="{% url "logout" %}">Logout</a>
      {% else %}
        <a href="{% url "login" %}">Log-in</a>
      {% endif %}
    </span>
  </div>
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}">
          {{ message|safe }}
          <a href="#" class="close">x</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
</body>
</html>