TreasureTrove/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/',
         include('social_django.urls', namespace='social')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
                                     name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('create/', views.product_create, name='create'),
    path('delete/', views.product_delete, name='delete'),
    path('', views.product_list_shop, name='product_list_shop'),
    path('market/', views.product_list_market, name='product_list_market'),
    path('ranking/', views.product_ranking, name='product_ranking'),
    path('<slug:category_slug>/', views.product_list_shop,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail_shop,
         name='product_detail_shop'),
    path('product/like/', views.product_like, name='product_like'),
]

shop/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.text import slugify
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from django.db.models import Avg

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique=True)
    icon = models.ImageField(blank=True)  # Default icon class

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Rating(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='ratings_given', on_delete=models.CASCADE)
    product = models.ForeignKey('Product',
                                on_delete=models.CASCADE,
                                related_name='rating')
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.rating} stars'

    class Meta:
        ordering = ['created', 'rating']


class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='product_created',
                             on_delete=models.CASCADE)
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    quantity_product = models.PositiveIntegerField(default=0,
                                                   validators=[MinValueValidator(0), MaxValueValidator(10000)])
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    address = models.CharField(max_length=100, default="Ha Noi")
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='product_liked',
                                        blank=True)
    total_likes = models.PositiveIntegerField(default=0)

    def average_rating(self):
        # Calculate the average rating for the product
        average = self.rating.aggregate(Avg('rating'))['rating__avg']
        return round(average, 2) if average is not None else "No rating"

    class Meta:
        ordering = ['name', 'user']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
            models.Index(fields=['-total_likes'])
        ]

    def __str__(self):
        return f'{self.user.username} - {self.name}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop:product_detail_shop', args=[self.id,
                                                         self.slug])


class Comment(models.Model):
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE,
                                related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='comment_created',
                             on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.user.name} on {self.product}'

shop/forms.py
from django import forms
from .models import Product
from django.utils.text import slugify
import requests
from django.core.files.base import ContentFile


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'name', 'slug', 'quantity_product', 'image', 'description', 'price', 'address',
                  'available']
        labels = {
            'name': 'Product Name',
            'image': 'Product Image',
            'description': 'Product description',
            'price': 'Product Price',
            'available': 'Available',
        }
        prepopulated_fields = {'slug': ('name'.lower(),)}

    def save(self, commit=True):
        product = super().save(commit=False)
        product.slug = slugify(product.name)  # Set the slug based on the name

        if product.quantity_product == 0:
            product.available = False

        if commit:
            product.save()

        return product


class ProductDeleteForm(forms.Form):
    class Meta:
        model = Product
        fields = ['name']
        labels = {
            'name': 'Product Name',
        }
        prepopulated_fields = {'slug': ('name'.lower(),)}
    confirmation = forms.BooleanField(
        required=True,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        label="I confirm that I want to delete this product."
    )

shop/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import get_object_or_404
from .forms import ProductCreateForm
from .models import Product
from .models import Category, Product
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from cart.forms import CartAddProductForm
import redis
from django.conf import settings

r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB)


@login_required
def product_create(request):
    if request.method == "POST":
        product_form = ProductCreateForm(request.POST, request.FILES)
        if product_form.is_valid():
            new_product = product_form.save(commit=False)
            new_product.user = request.user
            new_product.save()
            messages.success(request, 'Product added successfully')
            return redirect(new_product.get_absolute_url())
    else:
        product_form = ProductCreateForm()

    return render(request, 'shop/product/create.html',
                  {'section': 'product',
                   'product_form': product_form})


@login_required
def product_delete(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    # Check if the current user is the owner of the product
    if request.user != product.user:
        messages.error(request, "You don't have permission to delete this product.")
        return redirect('some_redirect_url')  # Specify the appropriate URL to redirect if permission is denied

    if request.method == "POST":
        form = ProductDeleteForm(request.POST)
        if form.is_valid():
            # Assuming your ProductDeleteForm has some validation logic, perform validation here

            # Delete the product
            product.delete()
            messages.success(request, 'Product deleted successfully')
            return redirect('some_redirect_url')  # Specify the appropriate URL to redirect after deletion
    else:
        form = ProductDeleteForm()

    return render(request, 'shop/product/delete.html',
                  {'section': 'product',
                   'product': product,
                   'form': form})


@login_required
def product_detail_shop(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug)
    cart_product_form = CartAddProductForm()
    total_views = r.incr(f'product:{product.id}:views')
    r.zincrby('product_ranking', 1, product.id)
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'total_views': total_views})


@login_required
def product_list_shop(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    user = request.user  # Get the currently logged-in user
    products = Product.objects.filter(user=user)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 20)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If the page parameter is not an integer, deliver the first page.
        products = paginator.page(1)
    except EmptyPage:
        # If the page is out of range (e.g., 9999), deliver the last page.
        products = paginator.page(paginator.num_pages)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


@login_required
def product_list_market(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()

    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 20)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If the page parameter is not an integer, deliver the first page.
        products = paginator.page(1)
    except EmptyPage:
        # If the page is out of range (e.g., 9999), deliver the last page.
        products = paginator.page(paginator.num_pages)
    return render(request,
                  'shop/product/list_product.html',
                  {'category': category,
                   'categories': categories,
                   'products_market': products})


@login_required
@require_POST
def product_like(request):
    product_id = request.POST.get('id')
    action = request.POST.get('action')
    if product_id and action:
        try:
            product = Product.objects.get(id=product_id)
            if action == 'like':
                product.users_like.add(request.user)
            else:
                product.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Product.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})


@login_required
def product_ranking(request):
    product_ranking = r.zrange('product_ranking', 0, -1,
                               desc=True)[:10]
    product_ranking_ids = [int(id) for id in product_ranking]
    most_viewed = list(Product.objects.filter(
        id__in=product_ranking_ids))
    most_viewed.sort(key=lambda x: product_ranking_ids.index(x.id))
    return render(request,
                  'shop/product/ranking_views.html',
                  {'section': 'products',
                   'most_viewed': most_viewed})

templates/shop/product/create.html
<!-- templates/account/shop/product/create.html -->
{% extends 'base.html' %}

{% block content %}
  <h1>Create a New Product</h1>
<div class="create-product">
    <form method="post" enctype="multipart/form-data">
    {{ product_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Save changes"></p>
    </form>
</div>
{% endblock %}

templates/shop/product/detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ product.title }}{% endblock %}
{% block content %}
    <div class="image-detail-block">
        <h1>{{ product.name }}</h1>
        <div class="detail">
            <div class="image-detail">
                <img src="{% thumbnail product.image 200x0 %}">
            </div>
            {% with total_likes=product.users_like.count users_like=product.users_like.all %}
            <div class="product-info">
                <div>
                    <span class="count">
                    <span class="total">{{ total_likes }}</span>
                    like{{ total_likes|pluralize }}
                    </span>
                    <span class="count">
                      {{ total_views }} view{{ total_views|pluralize }}
                    </span>
                <a href="#" data-id="{{ product.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
                  {% if request.user not in users_like %}
                    Like
                  {% else %}
                    Unlike
                  {% endif %}
                </a>
                <p class="price">${{ product.price }}</p>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                  {{ cart_product_form }}
                  {% csrf_token %}
                  <input type="submit" value="Add to cart">
                </form>
                <p class="{% if product.available == True %}available{% else %}fail{% endif %}">
                {% if product.available %}Available{% else %}Not Available{% endif %}
                    <p class="product-description">
                        {{ product.description|truncatewords_html:100 }}
                    </p>
                    <div>
                        {% for user in product.users_like.all %}
                        {% empty %}
                        Nobody likes this product yet.
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endwith %}
{% endblock %}
{% block domready %}
  var url = '{% url "shop:product_like" %}';
  var options = {
    method: 'POST',
    headers: {'X-CSRFToken': csrftoken},
    mode: 'same-origin'
  }
  document.querySelector('a.like')
          .addEventListener('click', function(e){
    e.preventDefault();
    var likeButton = this;
    // add request body
    var formData = new FormData();
    formData.append('id', likeButton.dataset.id);
    formData.append('action', likeButton.dataset.action);
    options['body'] = formData;
    // send HTTP request
    fetch(url, options)
    .then(response => response.json())
    .then(data => {
      if (data['status'] === 'ok')
      {
        var previousAction = likeButton.dataset.action;
        // toggle button text and data-action
        var action = previousAction === 'like' ? 'unlike' : 'like';
        likeButton.dataset.action = action;
        likeButton.innerHTML = action;
        // update like count
        var likeCount = document.querySelector('span.count .total');
        var totalLikes = parseInt(likeCount.innerHTML);
        likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
      }
    })
  });
{% endblock %}

templates/shop/product/list.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load custom_filters %}
{% block title %}
{% endblock %}
{% block content %}
  <div id="sidebar">
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list_shop" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"
        {% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
<div class="main-container">
<div class="short-bar">
    <div class="additional-links">
        <a href="?sort=newest">Newest</a>
        <a href="?sort=best-sale">Best sale</a>
        <a href="?sort=popular">Popular</a>
    </div>
        <div class="page-links">
        <span class="total-pages">{{ products.number }}/{{ products.paginator.num_pages }}</span>
        {% for i in products.paginator.page_range %}
            <a href="?page={{ i }}" {% if products.number == i %}class="current"{% endif %}></a>
        {% endfor %}
    </div>
</div>
    <div class="product-container">
      <div id="main" class="product-list">
        {% for product in products %}
          <div class="product-item">
            <a href="{{ product.get_absolute_url }}">
              <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_img.png" %}{% endif %}">
            </a>
            <p href="{{ product.get_absolute_url }}">{{ product.name }}</p>
            <div class="rating">
                <span title="{{ product.average_rating }}/5">
                    <i class="fa fa-star{% if product.average_rating < 0.5%}-o{% elif product.average_rating >= 0.5 and product.average_rating < 1 %}-half-o{% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if product.average_rating < 1.5%}-o{% elif product.average_rating >= 1.5 and product.average_rating < 2 %}-half-o{% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if product.average_rating < 2.5%}-o{% elif product.average_rating >= 2.5 and product.average_rating < 3 %}-half-o{% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if product.average_rating < 3.5%}-o{% elif product.average_rating >= 3.5 and product.average_rating < 4 %}-half-o{% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if product.average_rating < 4.5%}-o{% elif product.average_rating >= 4.5 and product.average_rating < 5 %}-half-o{% endif %}" aria-hidden="true"></i>
                </span>
                <div>{{ product.average_rating }}/5</div>
            </div>
            <p class="price">${{ product.price }}</p>
            <p>{{ product.address }}</p>
          </div>
        {% endfor %}
      </div>
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if products.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ products.previous_page_number }}">previous</a>
            {% endif %}

            {% with start=products.number|default:0|add:-2 end=products.number|default:0|add:2 %}

                {% for i in products.paginator.page_range %}
                    {% if i < start or i > end %}
                        {% if forloop.first and i > end %}
                            <span class="ellipsis">...</span>
                        {% endif %}
                        {% if forloop.last and i < start %}
                            <span class="ellipsis">...</span>
                        {% endif %}
                    {% elif i == start or i == end %}
                        <a href="?page={{ i }}">{{ i }}</a>
                    {% elif start < i and i < end %}
                        {% if products.number == i %}
                            <span class="current">{{ i }}</span>
                        {% else %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            {% endwith %}

            {% if products.has_next %}
                <a href="?page={{ products.next_page_number }}">next</a>
                <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

templates/shop/product/list_product.html
{% load static %}
{% block content %}
  <div id="sidebar">
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list_shop" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"
        {% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
<div class="main-container">
<div class="short-bar">
    <div class="additional-links">
        <a href="?sort=newest">Newest</a>
        <a href="?sort=best-sale">Best sale</a>
        <a href="?sort=popular">Popular</a>
    </div>
        <div class="page-links">
        <span class="total-pages">{{ products.number }}/{{ products.paginator.num_pages }}</span>
        {% for i in products.paginator.page_range %}
            <a href="?page={{ i }}" {% if products.number == i %}class="current"{% endif %}></a>
        {% endfor %}
    </div>
</div>
    <div class="product-container">
      <div id="main" class="product-list">
        {% for product in products %}
          <div class="product-item">
            <a href="{{ product.get_absolute_url }}">
              <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_img.png" %}{% endif %}">
            </a>
            <p href="{{ product.get_absolute_url }}">{{ product.name }}</p>
            <div class="rating">
                <span title="{{ product.average_rating }}/5">
                    <i class="fa fa-star{% if product.average_rating < 0.5%}-o{% elif product.average_rating >= 0.5 and product.average_rating < 1 %}-half-o{% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if product.average_rating < 1.5%}-o{% elif product.average_rating >= 1.5 and product.average_rating < 2 %}-half-o{% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if product.average_rating < 2.5%}-o{% elif product.average_rating >= 2.5 and product.average_rating < 3 %}-half-o{% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if product.average_rating < 3.5%}-o{% elif product.average_rating >= 3.5 and product.average_rating < 4 %}-half-o{% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if product.average_rating < 4.5%}-o{% elif product.average_rating >= 4.5 and product.average_rating < 5 %}-half-o{% endif %}" aria-hidden="true"></i>
                </span>
                <div>{{ product.average_rating }}/5</div>
            </div>
            <p class="price">${{ product.price }}</p>
            <p>{{ product.address }}</p>
          </div>
        {% endfor %}
      </div>
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if products.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ products.previous_page_number }}">previous</a>
            {% endif %}

            {% with start=products.number|default:0|add:-2 end=products.number|default:0|add:2 %}

                {% for i in products.paginator.page_range %}
                    {% if i < start or i > end %}
                        {% if forloop.first and i > end %}
                            <span class="ellipsis">...</span>
                        {% endif %}
                        {% if forloop.last and i < start %}
                            <span class="ellipsis">...</span>
                        {% endif %}
                    {% elif i == start or i == end %}
                        <a href="?page={{ i }}">{{ i }}</a>
                    {% elif start < i and i < end %}
                        {% if products.number == i %}
                            <span class="current">{{ i }}</span>
                        {% else %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            {% endwith %}

            {% if products.has_next %}
                <a href="?page={{ products.next_page_number }}">next</a>
                <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

templates/shop/product/ranking_views.html
{% extends "base.html" %}
{% block title %}Product ranking{% endblock %}
{% block content %}
  <h1>Product ranking views</h1>
  <ol>
    {% for product in most_viewed %}
      <li>
        <a href="{{ product.get_absolute_url }}">
          {{ product.name }}
        </a>
      </li>
    {% endfor %}
  </ol>
{% endblock %}